
unit_test:
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://0.0.0.0:2375"
  services:
    - name: 'docker:20.10.12-dind'
      command: [ '--tls=false', '--host=tcp://0.0.0.0:2375' ]
  stage: test
  image:
    # Gradle JDK 19
    name: gradle:jdk19
  tags:
    - kubernetes
  script:
    - env
    - mv src/main/resources/application.properties.dist src/main/resources/application.properties
    - gradle test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
    paths:
      - build/jacoco-report/

coverage:
  stage: test
  tags:
    - docker
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    # convert report from jacoco to cobertura, using relative project path
    # Change /src/main/java to /src/main/kotlin if you are using kotlin
    - python /opt/cover2cover.py build/jacoco-report/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > build/cobertura.xml
    - cat build/jacoco-report/index.html | grep -o 'Total[^%]*%'
  coverage: '/Total.*?([0-9]{1,3})%/'
  needs: [ "unit_test" ]
  dependencies:
    - unit_test
  artifacts:
    expire_in: 1 week
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

